/*========================== begin_copyright_notice ============================

Copyright (C) 2015-2021 Intel Corporation

SPDX-License-Identifier: MIT

============================= end_copyright_notice ===========================*/

// XFAIL: *

#include <cm/cm.h>

_GENX_MAIN_
void test() {
}

// We check that the Finalizer is run with -noschedule if and only if the
// -Qxcm_noschedule option is specified, and that the expected files are
// generated by deleting them (leaving things tidy)

// RUN: %cmc -emit-llvm -march=skl -- %s 2>&1 | FileCheck --check-prefix=SCHED %s

// RUN: %cmc -emit-llvm -march=skl -Qxcm_noschedule -- %s 2>&1 | FileCheck --check-prefix=NOSCHED %s

// RUN: %cmc -emit-llvm -march=skl /Qxcm_noschedule -- %s 2>&1 | FileCheck --check-prefix=NOSCHED %s

// SCHED-NOT: -noschedule
// SCHED: -platform SKL 

// NOSCHED: -noschedule
// NOSCHED-SAME: -platform SKL 
