#include <cm/cm.h>

_GENX_MAIN_
void test() {
}

// We check that the Finalizer is run with -noschedule if and only if the
// -Qxcm_noschedule option is specified, and that the expected files are
// generated by deleting them (leaving things tidy)

// RUN: %cmc -Qxcm_jit_target=skl %w 2>&1 | FileCheck --check-prefix=SCHED %w
// RUN: rm %W.isa %W_0.visaasm %W_0.asm %W_0.dat

// RUN: %cmc -Qxcm_jit_target=skl -Qxcm_noschedule %w 2>&1 | FileCheck --check-prefix=NOSCHED %w
// RUN: rm %W.isa %W_0.visaasm %W_0.asm %W_0.dat

// RUN: %cmc -Qxcm_jit_target=skl /Qxcm_noschedule %w 2>&1 | FileCheck --check-prefix=NOSCHED %w
// RUN: rm %W.isa %W_0.visaasm %W_0.asm %W_0.dat

// SCHED-NOT: -noschedule
// SCHED: -platform SKL 

// NOSCHED: -noschedule
// NOSCHED-SAME: -platform SKL 
