#=========================== begin_copyright_notice ============================
#
# Copyright (C) 2020-2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
#
#============================ end_copyright_notice =============================

name: Notify
on:
  status:
  pull_request_review:
env:
  NOTIFY: ${{ secrets.NOTIFY }}

jobs:
  notify:
    runs-on: [self-hosted, linux, small]
    steps:
      - name: Get branch name if status changed
        if: github.event_name == 'status'
        run: >
          echo "os_branch=${{ github.event.branches[0].name }}" >> $GITHUB_ENV
      - name: Get branch name if pr review state changed
        if: github.event_name == 'pull_request_review'
        env:
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: >
          echo "os_branch=$PR_HEAD_REF" >> $GITHUB_ENV
      - name: Notify
        if: ${{ env.NOTIFY != '' }}
        run: ${{ secrets.NOTIFY }}
