/*========================== begin_copyright_notice ============================

Copyright (C) 2015-2021 Intel Corporation

SPDX-License-Identifier: MIT

============================= end_copyright_notice ===========================*/

// XFAIL: *

#include <cm/cm.h>

_GENX_MAIN_
void test() {
}

#define STRING2(x) #x
#define STRING(x) STRING2(x)

#ifdef CM_GENX
#pragma message ( "CM_GENX defined with value " STRING(CM_GENX) )
#else
#warning CM_GENX not defined
#endif

#ifdef CM_GEN7_5
#warning CM_GEN7_5 defined
#endif

#ifdef CM_GEN8
#warning CM_GEN8 defined
#endif

#ifdef CM_GEN8_5
#warning CM_GEN8_5 defined
#endif

#ifdef CM_GEN9
#warning CM_GEN9 defined
#endif

#ifdef CM_GEN9_5
#warning CM_GEN9_5 defined
#endif

#ifdef CM_GEN10
#warning CM_GEN10 defined
#endif

#ifdef CM_GEN10_5
#warning CM_GEN10_5 defined
#endif

#ifdef CM_GEN11
#warning CM_GEN11 defined
#endif

// We test a number of different ways to specify a BXT jit target option.
// All are equivalent, and should produce the same results, so we only need
// one set of CHECK values for all of these tests.
// We check the expected Gen variant macros are defined (and no others), and
// that the Finalizer is called with the expected platform option.
// We also check that the expected files are generated by deleting them, 
// which also leaves things tidy for the next test.

// RUN: %cmc -emit-llvm -Qxcm_jit_target=bxt -- %s 2>&1 | FileCheck %s

// RUN: %cmc -emit-llvm -Qxcm_jit_target:bxt -- %s 2>&1 | FileCheck %s

// RUN: %cmc -emit-llvm -Qxcm_jit_targetbxt -- %s 2>&1 | FileCheck %s

// RUN: %cmc -emit-llvm -Qxcm_jit_target=gen9lp -- %s 2>&1 | FileCheck %s

// RUN: %cmc -emit-llvm -Qxcm_jit_target=GEN9LP -- %s 2>&1 | FileCheck %s

// RUN: %cmc -emit-llvm /Qxcm_jit_target=BXT -- %s 2>&1 | FileCheck %s

// RUN: %cmc -emit-llvm /Qxcm_jit_target:bxT -- %s 2>&1 | FileCheck %s

// RUN: %cmc -emit-llvm /Qxcm_jit_targetBxt -- %s 2>&1 | FileCheck %s

// RUN: %cmc -emit-llvm /Qxcm_jit_targetbXt -- %s 2>&1 | FileCheck %s

// RUN: %cmc -emit-llvm -Qxcm_jit_target -mcpu=BXT -- %s 2>&1 | FileCheck %s

// RUN: %cmc -emit-llvm -Qxcm_jit_target -mcpu=gEN9lP -- %s 2>&1 | FileCheck %s

// RUN: %cmc -emit-llvm -march=Bxt -Qxcm_jit_target -- %s 2>&1 | FileCheck %s

// RUN: %cmc -emit-llvm -Qxcm_jit_target -march=Gen9LP -- %s 2>&1 | FileCheck %s

// CHECK: cm_jit_target_bxt.cpp(11,9):  warning: CM_GENX defined with value 920 [-W#pragma-messages]
// CHECK: cm_jit_target_bxt.cpp(29,2):  warning: CM_GEN9 defined [-W#warnings]
// CHECK: 2 warnings generated.
// CHECK: -platform BXT
